"""Added field ru_critic_score to movies.

Revision ID: 7ff7669487c3
Revises: 9483fe5c4386
Create Date: 2022-03-03 11:40:21.187490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff7669487c3'
down_revision = '9483fe5c4386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('ru_critic_score', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'ru_critic_score')
    # ### end Alembic commands ###
